name: test_Workflow
on: workflow_call
jobs:
  test_reusable:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v7
      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: cache requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-${{hashFiles('requirements.txt')}}
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run first test case 
        run: pytest tests/test_data_quality.py -v 