name: test_workflow
on: push
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v7
      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: cache requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-${{hashFiles('requirements.txt')}}
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run first test case 
        run: pytest tests/test_data_quality.py -v 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v7
      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: cache requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-${{hashFiles('requirements.txt')}}
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run build script
        run: python build_output.py
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts_files_generated
          path: artifact/*.csv

  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v7
      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: cache requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-${{hashFiles('requirements.txt')}}
      - name: install requirements
        run: pip install -r requirements.txt
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts_files_generated
          path: data/
      - name: list file
        run: |
          cd data/ 
          ls
      - name: print deploy
        run: echo "done deploying"
   